### ISSUE TITLE
lyon_tessellation: panicked on an `Err` value: Internal(E03)

### ISSUE THREAD

**Issue by Lapz** [nical/lyon#358]
If you clone [Lapz/lyon_err](https://github.com/Lapz/lyon_err]) and  the program it panics with attempt 
unwrap on an `Err`
Here is the stack trace:
```rust 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Internal(E03)', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: std::panicking::try::do_call
             at libstd/panicking.rs:350
   6: std::panicking::try::do_call
             at libstd/panicking.rs:328
   7: <core::fmt::Write::write_fmt::Adapter<'a, T> as core::fmt::Write>::write_str
             at libcore/panicking.rs:71
   8: <lyon_tessellation::fixed::_16 as lyon_tessellation::fixed::FractionalBits>::bits
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9: <lyon_tessellation::fixed::_16 as lyon_tessellation::fixed::FractionalBits>::bits
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10: lyon_tessellation::path_stroke::tess_round_cap
             at /Users/lenardpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.1/src/basic_shapes.rs:689
  11: ggez::filesystem::Filesystem::is_file::{{closure}}
             at /Users/lenardpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/graphics/mesh.rs:96
  12: ggez::filesystem::Filesystem::is_file::{{closure}}
             at /Users/lenardpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/graphics/mesh.rs:296
  13: <ggez::graphics::SamplerCache<B>>::get_or_insert::{{closure}}
             at /Users/lenardpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/graphics/mod.rs:425
  14: lyon_err::Star::draw
             at src/main.rs:53
  15: <lyon_err::MainState as ggez::event::EventHandler>::draw
             at src/main.rs:103
  16: ggez::event::run
             at /Users/lenardpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/event.rs:283
  17: lyon_err::main
             at src/main.rs:118
  18: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  20: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  21: <alloc::string::String as core::fmt::Display>::fmt
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  22: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  23: lyon_err::GENERATOR::__getit
```

**Comment by nical** [comment]
Thanks a lot for filing this. I've been terribly busy lately so it took a while before I found the time to look at it unfortunately, but I believe I fixed the issue in #363. I also back-ported the fix to the `0.10` branch and published version `0.10.2` on crates.io, so you should be able to get the fix without breaking changes.
