### ISSUE TITLE
Path fails to tesselate

### ISSUE THREAD

**Issue by Yatekii** [nical/lyon#481]
Hi!

I found another path that does not tesselate:

```
Path {
    points: [
        (0.9177246,0.22070313),
        (0.9111328,0.21826172),
        (0.91625977,0.22265625),
        (0.9111328,0.22753906),
        (0.9309082,0.2397461),
        (0.92163086,0.24121094),
        (0.91796875,0.23486328),
        (0.91845703,0.23999023),
        (0.90649414,0.24633789),
        (0.9038086,0.23022461),
        (0.89575195,0.23779297),
        (0.88671875,0.23583984),
        (0.88427734,0.2277832),
        (0.88671875,0.22143555),
        (0.8964844,0.21972656),
        (0.904541,0.22460938),
        (0.9111328,0.21459961),
        (0.907959,0.24072266),
        (0.9094238,0.24169922),
        (0.9104004,0.24047852),
        (0.9111328,0.23950195),
        (0.91674805,0.24047852),
        (0.91259766,0.23803711),
        (0.8864746,0.22998047),
        (0.88793945,0.22998047),
        (0.8874512,0.22827148),
        (0.8852539,0.2265625),
        (0.8864746,0.22924805),
        (0.8869629,0.22607422),
        (0.88793945,0.22827148),
        (0.8894043,0.22729492),
        (0.8869629,0.22607422),
        (0.8918457,0.22680664),
        (0.89453125,0.2265625),
        (0.89282227,0.22558594),
        (0.8911133,0.2241211),
        (0.8898926,0.22436523),
        (0.89038086,0.22558594),
        (0.9238281,0.23022461),
        (0.9213867,0.23022461),
        (0.91918945,0.22729492),
        (0.92211914,0.22680664),
    ],
    verbs: [
        MoveTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        LineTo,
        Close,
        MoveTo,
        LineTo,
        LineTo,
        Close,
        MoveTo,
        LineTo,
        LineTo,
        Close,
        MoveTo,
        LineTo,
        LineTo,
        Close,
        MoveTo,
        LineTo,
        LineTo,
        Close,
        MoveTo,
        LineTo,
        LineTo,
        Close,
        MoveTo,
        LineTo,
        LineTo,
        Close,
        MoveTo,
        LineTo,
        LineTo,
        Close,
        MoveTo,
        LineTo,
        LineTo,
        LineTo,
        Close,
    ],
}
```

Unsure what I did wrong. All the other 10k paths in the same format (map tiles) draw properly.

**Comment by Yatekii** [comment]
I think the error cause is this:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 32 but the index is 32', /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/slice/mod.rs:2695:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: lyon_tessellation::path_fill::FillTessellator::tessellate_events
             at /home/yatekii/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.13.2/src/path_fill.rs:0
             at /home/yatekii/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.13.2/src/path_fill.rs:498
             at /home/yatekii/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.13.2/src/path_fill.rs:356
  10: sailor::vector_tile::transform::geometry_commands_to_drawable
             at /home/yatekii/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.13.2/src/path_fill.rs:330
             at src/vector_tile/transform.rs:129
```

**Comment by nical** [comment]
Sorry for taking so long, the new tessellator was merged into master and it doesn't have this issue. Release coming in a few days.

**Comment by Yatekii** [comment]
\o/ awesome! thanks so much man!
