### ISSUE TITLE
wgpu example panics because of outdated SwapChainTexture

### ISSUE THREAD

**Issue by Nilirad** [nical/lyon#602]
The `wgpu` example panics immediately after being started. Here is the message:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Outdated', examples\wgpu\src/main.rs:492:52`

<details>
<summary>Backtrace</summary>

```
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\mod.rs:1504
   5: std::sys_common::backtrace::_print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:511
  10: std::panicking::begin_panic_handler
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
  11: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:111
  12: core::option::expect_none_failed
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\option.rs:1268
  13: core::result::Result<wgpu::SwapChainFrame, wgpu::SwapChainError>::unwrap<wgpu::SwapChainFrame,wgpu::SwapChainError>
             at C:\Users\rinal\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:1005
  14: wgpu::main::{{closure}}
             at .\src\main.rs:492
  15: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
             at C:\Users\rinal\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:211
  16: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at C:\Users\rinal\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\boxed.rs:1015
  17: winit::platform_impl::platform::event_loop::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\rinal\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:595
  18: std::panic::{{impl}}::call_once<(),closure-0>
             at C:\Users\rinal\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  19: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\rinal\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:331
  20: winit::platform_impl::platform::raw_input::get_raw_mouse_button_state
  21: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\rinal\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  22: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\rinal\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  23: winit::platform_impl::platform::event_loop::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\rinal\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:593
  24: winit::platform_impl::platform::event_loop::EventLoopRunner<()>::events_cleared<()>
             at C:\Users\rinal\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:532
  25: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\Users\rinal\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:258
  26: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\rinal\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\platform_impl\windows\event_loop.rs:199
  27: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\rinal\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.20.0-alpha5\src\event_loop.rs:148
  28: wgpu::main
             at .\src\main.rs:451
  29: std::rt::lang_start::{{closure}}<()>
             at C:\Users\rinal\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  30: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:52
  31: std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:331
  32: std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:274
  33: std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panic.rs:394
  34: std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:51
  35: std::rt::lang_start<()>
             at C:\Users\rinal\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  36: main
  37: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  38: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  39: BaseThreadInitThunk
  40: RtlUserThreadStart
```

</details>

Toolchain: `stable-x86_64-pc-windows-msvc`
OS: Windows 10 version 2004, build 19041.450

**Comment by nical** [comment]
Thanks for filing this. I'll have a look shortly.
