### ISSUE TITLE
Assertion Failure during tesselation: !self.in_subpath

### ISSUE THREAD

**Issue by foobar27** [nical/lyon#657]
Hi, 
when I run `wgpu_svg` with the following SVG file, the assertion `!self.in_subpath` in `private.rs:55` in the `path` crate fails. I assume this is a bug in lyon and not in usvg or in the example application, but I did not verify.

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="216.665pt" height="155.823pt" viewBox="0 0 216.665 155.823" version="1.1">
  <defs>
    <g>
      <symbol overflow="visible" id="glyph3-1">
	<path style="stroke:none;" d="M 1.796875 -2.3125 C 1.796875 -2.328125 1.84375 -2.421875 1.84375 -2.5 C 1.84375 -2.671875 1.6875 -2.78125 1.53125 -2.78125 C 1.328125 -2.78125 1.28125 -2.625 1.25 -2.5625 L 0.484375 -0.40625 C 0.46875 -0.34375 0.46875 -0.328125 0.46875 -0.3125 C 0.46875 -0.234375 0.671875 -0.1875 0.671875 -0.1875 C 0.71875 -0.1875 0.734375 -0.21875 0.765625 -0.28125 Z M 1.796875 -2.3125 "/>
      </symbol>
    </g>
  </defs>
  <g id="surface1">
    <g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
      <use xlink:href="#glyph3-1" x="211.189" y="79.796"/>
    </g>
  </g>
</svg>
```
Here is the full backtrace:
```
thread 'main' panicked at 'assertion failed: !self.in_subpath', /home/sebastien/co/lyon/crates/path/src/private.rs:55:13
stack backtrace:
   0:     0x563b8a3b1280 - std::backtrace_rs::backtrace::libunwind::trace::h4dee703919bfd40a
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x563b8a3b1280 - std::backtrace_rs::backtrace::trace_unsynchronized::h457e839f1a563e20
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563b8a3b1280 - std::sys_common::backtrace::_print_fmt::h86a55fb30f8393c8
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563b8a3b1280 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b3d6cac46d277e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x563b8a3d064f - core::fmt::write::h127419eb46f2ecc9
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/fmt/mod.rs:1092:17
   5:     0x563b8a3ae0e5 - std::io::Write::write_fmt::h6010cfbb4726588b
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/io/mod.rs:1578:15
   6:     0x563b8a3b328b - std::sys_common::backtrace::_print::h79b4f9652330cc9d
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563b8a3b328b - std::sys_common::backtrace::print::h330bb326a76af8cf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563b8a3b328b - std::panicking::default_hook::{{closure}}::heb6a42a7d50a472e
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:208:50
   9:     0x563b8a3b2d53 - std::panicking::default_hook::h17e521ba6d68d6e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:225:9
  10:     0x563b8a3b383d - std::panicking::rust_panic_with_hook::h70db735e3a6e70cb
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:591:17
  11:     0x563b8a3b3407 - std::panicking::begin_panic_handler::{{closure}}::h777c71c8e5a7e25c
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:495:13
  12:     0x563b8a3b173c - std::sys_common::backtrace::__rust_end_short_backtrace::h3e9bf30168899554
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563b8a3b3399 - rust_begin_unwind
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
  14:     0x563b89664801 - core::panicking::panic_fmt::h5322a082d19786c3
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
  15:     0x563b8966474d - core::panicking::panic::haebb15b6842d6229
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:50:5
  16:     0x563b8a24c3a4 - lyon_path::private::DebugValidator::build::hd8fd495df828912a
                               at /home/sebastien/co/lyon/crates/path/src/private.rs:55:13
  17:     0x563b8a24c3a4 - lyon_tessellation::event_queue::EventQueueBuilder::build::h971f7a0ed3d3c4c0
                               at /home/sebastien/co/lyon/crates/tessellation/src/event_queue.rs:474:9
  18:     0x563b896e59c0 - lyon_tessellation::fill::FillTessellator::tessellate::hed735fd264504b4d
                               at /home/sebastien/co/lyon/crates/tessellation/src/fill.rs:553:23
  19:     0x563b8967bce9 - wgpu_svg::main::h0f01b4d7552801bb
                               at /home/sebastien/co/lyon/examples/wgpu_svg/src/main.rs:130:17
  20:     0x563b89672e0b - core::ops::function::FnOnce::call_once::ha50f7f5faad5fabd
                               at /home/sebastien/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  21:     0x563b89687b4e - std::sys_common::backtrace::__rust_begin_short_backtrace::h0c5693a541493849
                               at /home/sebastien/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  22:     0x563b896711c1 - std::rt::lang_start::{{closure}}::hcb113ba2dc4440b5
                               at /home/sebastien/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  23:     0x563b8a3b3c3a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc915e668c7ca11
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/ops/function.rs:259:13
  24:     0x563b8a3b3c3a - std::panicking::try::do_call::h6b0f430d48122ddf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:379:40
  25:     0x563b8a3b3c3a - std::panicking::try::h6ba420e2e21b5afa
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:343:19
  26:     0x563b8a3b3c3a - std::panic::catch_unwind::h8366719d1f615eee
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panic.rs:431:14
  27:     0x563b8a3b3c3a - std::rt::lang_start_internal::h965c28c9ce06ee73
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/rt.rs:51:25
  28:     0x563b896711a0 - std::rt::lang_start::hb4a5863315bf1487
                               at /home/sebastien/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  29:     0x563b8967f26c - main
  30:     0x7ff876ac2b25 - __libc_start_main
  31:     0x563b89664f0e - _start
  32:                0x0 - <unknown>
```

**Comment by nical** [comment]
Thanks for filing this. Yeah it's likely a bug in lyon's path building code, I'll look into this shortly.
