### ISSUE TITLE
Crash with path builder, !self.in_subpath

### ISSUE THREAD

**Issue by dabreegster** [nical/lyon#806]
Hi! I'm upgrading from 0.16 to 1.0 and hitting a crash with path building. The stack trace:

```
thread 'main' panicked at 'assertion failed: !self.in_subpath', /home/dabreegster/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_path-1.0.0/src/private.rs:63:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: lyon_path::private::DebugValidator::build
             at /home/dabreegster/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_path-1.0.0/src/private.rs:63:13
   4: <lyon_path::path::BuilderImpl as lyon_path::builder::Build>::build
             at /home/dabreegster/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_path-1.0.0/src/path.rs:592:9
   5: lyon_path::builder::NoAttributes<B>::build
             at /home/dabreegster/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_path-1.0.0/src/builder.rs:351:9
```

I printed some input that's causing the problem. Hopefully the below is a usable reproduction of the bug, let me know if not.

```
use lyon::math::{point, Point};
use lyon::path::Path;

let mut builder = Path::builder();
builder.begin(point(0.0, 189.6));
builder.line_to(point(73.6, 189.6));
builder.line_to(point(147.2, 189.6));
builder.line_to(point(220.8, 189.6));
builder.line_to(point(294.4, 189.6));
builder.line_to(point(368, 189.6));
builder.line_to(point(441.6, 189.6));
builder.build();
```

Thanks for all of your work with this library and congratulations on 1.0!

**Comment by nical** [comment]
Hi! This is because of a pretty important that happened in the 0.17 release: the `PathBuilder` interface is now a lot more strict than it used to be, and in particular it forces you to always start sub-paths with `begin` and always end them with `end`.

If you want to get a more canvas/SVG-like path building API, you can use the [`WithSvg`](https://docs.rs/lyon_path/latest/lyon_path/builder/struct.WithSvg.html) adapter.

Your code would look something like:

```rust
use lyon::math::{point, Point};
use lyon::path::Path;

// Note: with_svg wraps the low level building implementation with an adapter that deals
// with ending sub-paths automatically.
let mut builder = Path::builder().with_svg();
builder.move_to(point(0.0, 189.6));
builder.line_to(point(73.6, 189.6));
builder.line_to(point(147.2, 189.6));
builder.line_to(point(220.8, 189.6));
builder.line_to(point(294.4, 189.6));
builder.line_to(point(368, 189.6));
builder.line_to(point(441.6, 189.6));
builder.build();
```

**Comment by dabreegster** [comment]
Thanks for the fast reply! This appears to work; I'll reopen or file another if I have more trouble upgrading.
