### ISSUE TITLE
Panic parsing "0 0M": `end() called without begin()` in lyon_path-1.0.5/src/private.rs

### ISSUE THREAD

**Issue by ogoffart** [nical/lyon#919]
Given this code:

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut builder = lyon_path::Path::builder();
    let mut parser = lyon_extra::parser::PathParser::new();
    parser.parse(
        &lyon_extra::parser::ParserOptions::DEFAULT,
        &mut lyon_extra::parser::Source::new("0 0M".chars()),
        &mut builder,
    )?;
    Ok(())
}
```

I'd expect this code to return an error, but not panic:

```
thread 'main' panicked at /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_path-1.0.5/src/private.rs:37:13:
end() called without begin()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
   3: lyon_path::private::DebugValidator::end
             at /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_path-1.0.5/src/private.rs:37:13
   4: <lyon_path::path::BuilderImpl as lyon_path::builder::PathBuilder>::end
             at /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_path-1.0.5/src/path.rs:536:9
   5: <lyon_path::builder::NoAttributes<B> as lyon_path::builder::PathBuilder>::end
             at /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_path-1.0.5/src/builder.rs:390:9
   6: lyon_extra::parser::PathParser::parse
             at /home/olivier/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lyon_extra-1.0.2/src/parser.rs:169:13
   7: bug::main
             at ./src/main.rs:4:5
```

(this was found by fuzzing slint that depends on lyon. Original report in https://github.com/slint-ui/slint/issues/6591)

**Comment by nical** [comment]
Hi, thanks for reporting this, I'll have a look soon-ish.
